fix: Update the dots container dynamically when dimensions change
KeyValueSoftwareSystems/react-dot-matrix-chart pull request #17
Opened 2023-12-07 10:41 UTC by anjuca154

​

## Pull Request Checklist

- [ ] **Read the contributing guidelines.**
- [x] **Linked to an issue:** Fixes # (replace with the issue number, if applicable)
- [x] **Branch is up-to-date with the base branch:** `main`
- [x] **Changes pass tests locally:** `npm test` or `yarn test`
- [ ] **Documentation has been updated, if necessary**
- [ ] **Code follows the style guide of the project**
      ​

## Description
Update the dots container dynamically when dimensions change
​

## Screenshots (if applicable)

​

​

## Additional Notes

​

​

## Related Issues or PRs

​

​

## Reviewer Guidelines

​

​

## Testing Instructions

​

​

## Checklist for Reviewers

​

- [ ] Code follows project conventions and style
- [ ] Changes do not introduce new warnings or errors
- [ ] Unit tests cover the changes
- [ ] Documentation is updated
      ​

## By submitting this pull request, I confirm that my contribution is made under the terms of the MIT License.

2023-12-29 04:45 UTC, ReshmaJoshy commented on src/lib/dot-matrix/custom-hooks/useChartContainerWidth.ts
> +    if (typeof window !== undefined) {
```suggestion
    if (typeof window !== 'undefined') {
```

typeof returns string

2023-12-29 05:02 UTC, bilta-keyvalue requested changes

2023-12-29 05:02 UTC, bilta-keyvalue commented on src/lib/dot-matrix/custom-hooks/useChartContainerWidth.ts
> +  dependencyArray: Array<boolean | string | number | undefined>
Is undefined expected as an array element ?

2023-12-29 05:02 UTC, bilta-keyvalue commented on src/lib/dot-matrix/custom-hooks/useDotMatrix.ts
> +          1 - (currentDots[i] - Math.floor(currentDots[i]));
Math.floor(currentDots[i]) this is done in multiple places. Can we assign it to a variable and reuse ?

2023-12-29 12:27 UTC, manacy-keyvalue approved these changes

2024-01-03 05:22 UTC, ReshmaJoshy approved these changes

2024-01-04 09:11 UTC, bilta-keyvalue approved these changes

2024-01-04 09:32 UTC, merged